name: E-Commerce-app-cd-cd

on:
  push:
    branches: [ "master" ]
    paths:
      - "src/**"
  pull_request:
    branches: [ "master" ]
    paths:
      - "src/**"
  workflow_dispatch:

jobs:
  test-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm install
      - run: npm run lint
      - run: node --max_old_space_size=4096 node_modules/@angular/cli/bin/ng test --browsers ChromeNoGpu --source-map=false --watch


